services:
  - type: web
    name: tldr-chinese-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind=0.0.0.0:10000 --workers=4 --threads=4 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: DEEPL_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false

  - type: static
    name: tldr-chinese-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-store, no-cache, must-revalidate
          - key: Pragma
            value: no-cache
          - key: Expires
            value: "0"
    env: node
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://tldr-chinese-api.onrender.com
